from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayerWindow(object):
    def setupUi(self, video_wnd):
        video_wnd.setObjectName("video_wnd")
        video_wnd.setWindowModality(QtCore.Qt.NonModal)
        video_wnd.resize(805, 423)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(video_wnd.sizePolicy().hasHeightForWidth())
        video_wnd.setSizePolicy(sizePolicy)
        video_wnd.setMinimumSize(QtCore.QSize(805, 423))
        video_wnd.setMaximumSize(QtCore.QSize(805, 423))
        video_wnd.setSizeIncrement(QtCore.QSize(0, 0))
        video_wnd.setBaseSize(QtCore.QSize(0, 0))
        video_wnd.setLayoutDirection(QtCore.Qt.LeftToRight)
        video_wnd.setAutoFillBackground(False)
        video_wnd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(video_wnd)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(video_wnd)
        self.verticalFrame.setObjectName("verticalFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalFrame)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.videoPlayer = QtWidgets.QLabel(self.verticalFrame)
        self.videoPlayer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPlayer.sizePolicy().hasHeightForWidth())
        self.videoPlayer.setSizePolicy(sizePolicy)
        self.videoPlayer.setMinimumSize(QtCore.QSize(640, 350))
        self.videoPlayer.setMaximumSize(QtCore.QSize(640, 350))
        self.videoPlayer.setSizeIncrement(QtCore.QSize(0, 0))
        self.videoPlayer.setBaseSize(QtCore.QSize(0, 0))
        self.videoPlayer.setStyleSheet("")
        self.videoPlayer.setText("")
        self.videoPlayer.setObjectName("videoPlayer")
        self.horizontalLayout_3.addWidget(self.videoPlayer)
        self.horizontalFrame = QtWidgets.QFrame(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(140, 350))
        self.horizontalFrame.setMaximumSize(QtCore.QSize(140, 350))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalFrame)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnBack = QtWidgets.QPushButton(self.horizontalFrame)
        self.btnBack.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBack.sizePolicy().hasHeightForWidth())
        self.btnBack.setSizePolicy(sizePolicy)
        self.btnBack.setMinimumSize(QtCore.QSize(140, 0))
        self.btnBack.setMaximumSize(QtCore.QSize(140, 50))
        self.btnBack.setAcceptDrops(False)
        self.btnBack.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnBack.setAutoFillBackground(False)
        self.btnBack.setStyleSheet("font-size:10pt; \n"
                                   "font-weight:600; \n"
                                   "color:#4d4d4d;\n"
                                   "background-color: rgb(231, 247, 255);")
        self.btnBack.setObjectName("btnBack")
        self.verticalLayout.addWidget(self.btnBack)
        self.btnContinue = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnContinue.sizePolicy().hasHeightForWidth())
        self.btnContinue.setSizePolicy(sizePolicy)
        self.btnContinue.setMinimumSize(QtCore.QSize(140, 40))
        self.btnContinue.setMaximumSize(QtCore.QSize(140, 50))
        self.btnContinue.setToolTipDuration(0)
        self.btnContinue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnContinue.setStyleSheet("font-size:10pt; \n"
                                       "font-weight:600; \n"
                                       "color:#4d4d4d;\n"
                                       "background-color: rgb(231, 247, 255);")
        self.btnContinue.setObjectName("btnContinue")
        self.verticalLayout.addWidget(self.btnContinue)
        self.btnPause = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPause.sizePolicy().hasHeightForWidth())
        self.btnPause.setSizePolicy(sizePolicy)
        self.btnPause.setMinimumSize(QtCore.QSize(140, 50))
        self.btnPause.setMaximumSize(QtCore.QSize(140, 50))
        self.btnPause.setStyleSheet("font-size:10pt; \n"
                                    "font-weight:600; \n"
                                    "color:#4d4d4d;\n"
                                    "background-color: rgb(231, 247, 255);")
        self.btnPause.setObjectName("btnPause")
        self.verticalLayout.addWidget(self.btnPause)
        self.btnSave = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setMinimumSize(QtCore.QSize(140, 50))
        self.btnSave.setMaximumSize(QtCore.QSize(140, 50))
        self.btnSave.setStyleSheet("font-size:10pt; \n"
                                   "font-weight:600; \n"
                                   "color:#4d4d4d;\n"
                                   "background-color: rgb(231, 247, 255);")
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        self.horizontalLayout_3.addWidget(self.horizontalFrame)
        self.horizontalLayout.addWidget(self.verticalFrame)

        self.retranslateUi(video_wnd)
        QtCore.QMetaObject.connectSlotsByName(video_wnd)

    def retranslateUi(self, video_wnd):
        _translate = QtCore.QCoreApplication.translate
        video_wnd.setWindowTitle(_translate("video_wnd", "Player"))
        self.btnBack.setText(_translate("video_wnd", "Назад"))
        self.btnContinue.setText(_translate("video_wnd", "Продолжить"))
        self.btnPause.setText(_translate("video_wnd", "Пауза"))
        self.btnSave.setText(_translate("video_wnd", "Сохранить"))
